title: "GET :: Genomes Environments Traits"
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/pgpconference" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: PGorg
# flickr_username: personalgenomes
# # github_username:  jekyll
# author: "Personal Genome Project: Global Network"
# google_analytics: UA-145673922-1

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # See https://github.com/jekyll/minima/blob/master/_config.yml for a full list
  social_links:
    twitter: attendGET
    github:  jekyll
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
markdown: kramdown
theme: minima

plugins:
  - github-pages
  - jekyll-admin
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings


exclude:
  #   - Gemfile
  #   - Gemfile.lock
  #   - vendor/bundle/
  #   - vendor/cache/
  #   - vendor/gems/
  #   - vendor/ruby/
  # - accessibility
  - docs
  - node_modules
  - README.md
  - ref
  - scratch
  - ["docs", "ref", "scratch"]

sass:
  style: expanded
  sourcemap: true

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

collections:
  speakers2016:
    output: false
  speakers2015:
    output: false
  speakers2014:
    output: false
  speakers2013:
    output: false
  speakers2012:
    output: false
  speakers2011:
    output: false
  speakers2010:
    output: false
  organizers2016:
    output: false
  organizers2015:
    output: false
  organizers2014:
    output: false
  past-conferences2016:
    output: true
  sponsors2016:
    output: false
  sponsors2015:
    output: false
  sponsors2014:
    output: false
  sponsors2013:
    output: false
  sponsors2012:
    output: false
  sponsors2011:
    output: false
  sponsors2010:
    output: false
  labs2016:
    output: false
  labs2014:
    output: false
  labs2013:
    output: false
  labs2012:
    output: false
  labs2011:
    output: false
  labs2010:
    output: false
  expos2016:
    output: false
  awards2016:
    output: false
  judges2016:
    output: false
  media-partners2016:
    output: false
